create table if not exists place (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id),
    constraint uk_place_name unique (name)
);

create table if not exists person_name (
    id bigint generated by default as identity,
    name_value varchar(255) not null,
    primary key (id),
    constraint uk_person_name_value unique (name_value)
);

create table if not exists person_surname (
    id bigint generated by default as identity,
    surname_value varchar(255) not null,
    primary key (id),
    constraint uk_person_surname_value unique (surname_value)
);

create table if not exists death (
    id bigint generated by default as identity,
    death_date_value date,
    death_date_end date,
    death_date_start date,
    death_date_type varchar(32),
    death_place_id bigint,
    primary key (id),
    constraint fk_death_place foreign key (death_place_id) references place (id)
);

create table if not exists divorce (
    id bigint generated by default as identity,
    divorce_date_value date,
    divorce_date_end date,
    divorce_date_start date,
    divorce_date_type varchar(32),
    primary key (id)
);

create table if not exists person (
    id bigint generated by default as identity,
    birth_date_value date,
    birth_date_end date,
    birth_date_start date,
    birth_date_type varchar(32),
    created_at timestamp with time zone not null,
    external_uuid varchar(255),
    gender boolean,
    married_last_name varchar(255),
    updated_at timestamp with time zone not null,
    birth_place_id bigint,
    death_id bigint,
    father_id bigint,
    first_name_id bigint,
    last_name_id bigint,
    mother_id bigint,
    primary key (id),
    constraint uk_person_death unique (death_id),
    constraint fk_person_birth_place foreign key (birth_place_id) references place (id),
    constraint fk_person_death foreign key (death_id) references death (id),
    constraint fk_person_father foreign key (father_id) references person (id),
    constraint fk_person_first_name foreign key (first_name_id) references person_name (id),
    constraint fk_person_last_name foreign key (last_name_id) references person_surname (id),
    constraint fk_person_mother foreign key (mother_id) references person (id)
);

create table if not exists marriage (
    id bigint generated by default as identity,
    registration_date_value date,
    registration_date_end date,
    registration_date_start date,
    registration_date_type varchar(32),
    divorce_id bigint,
    registration_place_id bigint,
    spouse_a_id bigint,
    spouse_b_id bigint,
    primary key (id),
    constraint uk_marriage_divorce unique (divorce_id),
    constraint fk_marriage_divorce foreign key (divorce_id) references divorce (id),
    constraint fk_marriage_place foreign key (registration_place_id) references place (id),
    constraint fk_marriage_spouse_a foreign key (spouse_a_id) references person (id),
    constraint fk_marriage_spouse_b foreign key (spouse_b_id) references person (id)
);
